config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
  root to: 'pldates#index'
  resources :pldates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pldate.rb
class Pldate < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 30 }
  validates :name, presence: true
  validates :name, length: { maximum: 40 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password validations: true

  has_many :pldates 
  def self.new_remember_token
  SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user
  before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
  end

  def signed_in?
    @current_user.present?
  end

  private

    def require_sign_in!
      redirect_to login_path unless signed_in?
    end

    def set_locale
      I18n.locale = current_user&.locale || :ja
    end
end

app/controllers/pldates_controller.rb
class PldatesController < ApplicationController

  def index
    @q = current_user.pldates.ransack(params[:q])
    @pldates = @q.result(distinct: true).page(params[:page]).per(9)

  end

  def new
    @pldate = Pldate.new
  end

  def create
    @pldate = current_user.pldates.new(pldate_params)

    if @pldate.save
      logger.debug "pldate: #{@pldate.attributes.inspect}"
      redirect_to @pldate, notice: "登録しました"
    else
      render 'new'
    end
  end

  def show
    @pldate = current_user.pldates.find(params[:id])
  end


  def edit
    @pldate = current_user.pldates.find(params[:id])
  end

  def update
    pldate = current_user.pldates.find(params[:id])
    pldate.update!(pldate_params)
    redirect_to pldates_url, notice: "更新しました"
  end

  def destroy
    pldate = current_user.pldates.find(params[:id])
    pldate.destroy
    redirect_to pldates_url, notice: "削除しました"
  end

  private

  def pldate_params
    params.require(:pldate).permit(:name, :url, :title, pldates_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]
  before_action :set_user, only: [:create]

  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to root_path
    else
      flash.now[:danger] = t('.flash.invalid_password')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end

  private

    def set_user
      @user = User.find_by!(email: session_params[:email])
    rescue
      flash.now[:danger] = t('.flash.invalid_mail')
      render action: "new"
    end

    def session_params
      params.require(:session).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]

  def new
   @user = User.new
  end

 def create
   @user = User.new(user_params)
   if @user.save
     redirect_to login_path
   else
     render 'new'
   end
 end

 private

   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/pldates_helper.rb
module PldatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweetssessions_helper.rb
module TweetssessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TRPGteller
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar.navbar-expand-md.navbar-llight.bg-light
      .navbar-brand
        a href="/"T R P G teller
      ul.navbar-nav.ml-auto
      - if @current_user
        .nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link h5 mt-1 mr-3 '
      - else
        .nav-item= link_to "新規登録", new_user_path, method: :get, class: 'nav-link h5 mr-3'
        .nav-item= link_to "ログイン", login_path, method: :get, class: 'nav-link h5'
    .container
        -if flash.notice.present?
          .alert.alert-success= flash.notice
        = yield

app/views/pldates/_form.html.slim
  = form_with model: pldate, local: true do |f|
    - if pldate.errors.present?
      ul#error_explanation
        - pldate.errors.full_messages.each do |message|
          p= message

    .form_group
      = f.label :title
      = f.text_field :title, class: 'form-control', id: 'pldate_title'
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', id: 'pldate_name'
    .form-group
      = f.label :url
      = f.text_area :url, rows: 30, class: 'form-control', id: 'pldate_url'

      = f.submit nil, class: 'btn btn-outline-primary mr-2'
      = link_to '取り消し', pldates_path, class: 'btn btn-outline-danger'

app/views/pldates/edit.html.slim
.textform 
  br
  h4 編集画面
  br
  br
  = render partial: 'form', locals: { pldate: @pldate }

app/views/pldates/index.html.slim
  .container_login
    p 簡易シナリオ作成・保管サイト
    .mb-5
    = link_to '新規登録', new_pldate_path, class: 'btn btn-outline-primary'
    .
      = paginate @pldates
      = page_entries_info @pldates
    .line
      .row
        - @pldates.each do |pldate|
          .col-sm-4.mb-3
            .border.border-dark.rounded-lg
              .card-body
                .card-title
                  td= pldate.title
                .card-text
                  |推奨人数
                  br
                  th= pldate.name
                  br
                  td
                    = link_to '詳細', pldate, class: 'btn btn-light p-0 mr-4'
                    = link_to '編集', edit_pldate_path(pldate), class: 'btn btn-outline-info p-0 mr-4'
                    = link_to '削除', pldate, method: :delete, data: { confirm: "削除しても良いですか？" }, class: 'btn btn-outline-danger p-0 '
    .right
      .right_contents
        p TRPGシナリオサイト
        .mb-3
        .span
          = link_to image_tag("scenarch.png"), "http://scenarch.com/"
        .mb-3
        p 立ち絵素材
        .mt-2
        .spans
          = link_to image_tag("ranuki.jpg"), "http://ranuking.ko-me.com/"
        .mb-3
        p キャラメイク
        .mt-2
        .spanm
          = link_to image_tag("charat.png"), "https://charat.me/"
        .mt-2
        p フリーBGM
        .mt-2
        .spanm
          = link_to image_tag("musicbox.png"), "http://amachamusic.chagasi.com/index.html"

app/views/pldates/new.html.slim
.textform
  br
  br
  h4 登録画面
  br
  br
  = render partial: 'form', locals: { pldate: @pldate }

app/views/pldates/show.html.slim
.textform
  .mb-4
  br
  h4　詳細
  .mb-5

  br
  table.table.table-hover
    tbody
      tr
        th= Pldate.human_attribute_name(:title)
        td= @pldate.title
      tr
        th= Pldate.human_attribute_name(:name)
        td= @pldate.name
      tr
        th= Pldate.human_attribute_name(:url)
        td= auto_link(simple_format(h(@pldate.url), {}, sanitize: false, wrapper_tag: "div"))
  = link_to '編集', edit_pldate_path, class: 'btn btn-outline-info mr-3'
  = link_to '削除', @pldate, method: :delete, data: { confirm: "削除しても良いですか？" }, class: 'btn btn-outline-danger'
  br
  = link_to 'TOP', pldates_path, class: 'btn btn-outline-primary mt-2 mr-5'

app/views/users/new.html.slim
- if @user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.each do |message|
      p= message
.container_login
  .left_content
    = form_for @user, url: users_path do |f|
      .form-group
        = f.label :name, "ユーザー名"
        = f.text_field :name, size: 27, class: 'form-control'
      .form-group
        = f.label :email, "メールアドレス"
        = f.email_field :email, size: 27, class: 'form-control'
      .form-group
        = f.label :password, "パスワード"
        = f.password_field :password, size: 27, class: 'form-control'
      .form-group
        = f.label :password_confirmation, "パスワード（確認）"
        = f.text_field :password_confirmation, size: 27, class: 'form-control'
        = f.submit "ユーザー登録", :class => "btn-circle-border-doubled"
.right_content 
    .foo
      span.letter data-letter="L"  L
      span.letter data-letter="e"  e
      span.letter data-letter="t"  t
      span.letter data-letter="'"  '
      span.letter data-letter="s"  s
      .border-bottom
      span.letter data-letter="P"  P
      span.letter data-letter="L"  L
      span.letter data-letter="A"  A
      span.letter data-letter="Y"  Y
      .border-bottom
      span.letter data-letter="T"  T
      span.letter data-letter="R"  R
      span.letter data-letter="P"  P
      span.letter data-letter="G"  G